#environment:
#  VisualStudioVersion: 11.0



platform:
  - x86
  - x64


configuration:
  - Debug
  - Release

before_build:
  - cmd: cd CefSharp.MinimalExample.Wpf
  - cmd: nuget install CefSharp.Wpf.%Platform% -Pre -o ..\packages
  - cmd: cd ..
#  - cmd: nuget restore

# MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed

build:
#  verbosity: detailed
  verbosity: minimal

artifacts:
  - path: *.exe

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
