#environment:
#  VisualStudioVersion: 11.0



platform:
  - x86


configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore
  - cmd: dir /b "C:\"
  - cmd: dir /b \progra~2
  - cmd: %path%

# MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed

build:
#  verbosity: detailed
  verbosity: minimal
  
matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
