#environment:
#  VisualStudioVersion: 11.0



platform:
  - x86


configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore

# MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed

#build:
#  verbosity: detailed
  
matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
