#environment:
#  VisualStudioVersion: 11.0



platform:
  - x86


configuration:
  - Debug
  - Release

before_build:
  - cmd: REM nuget restore
  - cmd: dir /b /s "C:\Tools\xUnit"


# MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed

build:
#  verbosity: detailed
  verbosity: minimal
  
matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
