environment:
  VisualStudioVersion: 11.0

platform:
  - x86


configuration:
  - Debug
#  - Release

# MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed

verbosity: detailed
  
matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
